### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by hplato** [tommyblue/Bind-Log-Analyzer#7]
Hi, I just downloaded and installed this. Thanks for the easy to follow instructions!

I have 4 questions;

1.  Is it possible to configure the timezone. It would be nice to have my local timezone instead of UTC
2. Have you thought about adding a search? It would be great to search for a query domain or specific IP addresses
3. Have you thought about filtering -- so filter by IP address, or a datepicker for the time?
4.Are there any issues with duplicates? I was going to cron the file upload every day.

With these three changes, this is a spectacular tool!

**Comment by tommyblue** [comment]
Hi @hplato how you can probably see I'm not actively working on these project, but your suggested features are very interesting (and welcome!), so I'm going to try and find some spare time to add them.
If you would like to try to learn some ruby feel free to open a PR :)

**Comment by AysadKozanoglu** [comment]
i get this error if i try to start 
<pre>
bind_log_analyzer --config /source/Bind-Log-Analyzer/database.yml --file /var/log/named.log 

/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/errors.rb:28:in `initialize': wrong number of arguments (given 1, expected 2) (ArgumentError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/connection_specification.rb:203:in `exception'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/connection_specification.rb:203:in `raise'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/connection_specification.rb:203:in `rescue in spec'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/connection_specification.rb:190:in `spec'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:950:in `establish_connection'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-5.2.0/lib/active_record/connection_handling.rb:60:in `establish_connection'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bind_log_analyzer-0.2.4/lib/bind_log_analyzer/connector.rb:33:in `connect'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bind_log_analyzer-0.2.4/lib/bind_log_analyzer/connector.rb:15:in `setup_db'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bind_log_analyzer-0.2.4/lib/bind_log_analyzer/base.rb:29:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bind_log_analyzer-0.2.4/bin/bind_log_analyzer:132:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/bind_log_analyzer-0.2.4/bin/bind_log_analyzer:132:in `<top (required)>'
	from /usr/local/bin/bind_log_analyzer:23:in `load'
	from /usr/local/bin/bind_log_analyzer:23:in `<main>'
</pre>

**Comment by emeidi** [comment]
@AysadKozanoglu `gem install mysql2`
